sites/gocd-interface/apps/project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from apps.project import views


urlpatterns = patterns('',
    url(r'^$', login_required(views.ProjectListView.as_view()), name="project-list"),
    url(r'^create/', login_required(views.ProjectCreateView.as_view()), name="create"),
    url(r'^(?P<pk>\d+)/settings/', login_required(views.ProjectSettingsView.as_view()), name="settings"),
    url(r'^(?P<pk>\d+)/', login_required(views.ProjectDetailView.as_view()), name="detail"),
)

sites/gocd-interface/apps/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

from apps.decorators import login_forbidden
from apps import views


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', login_forbidden(views.LoginView.as_view()), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^forgotten-password/$', views.ForgottenPasswordView.as_view(), name="forgotten-password"),
    url(r'^reset-forgotten-password/(?P<unique_code>[a-zA-Z0-9\-]+)/', views.PasswordResetView.as_view(), name="reset-forgotten-password"),
    url(r'^password-set/(?P<unique_code>[a-zA-Z0-9\-]+)/', views.PasswordResetView.as_view(), name="set-password"),
    url(r'^gocd/$', views.HomePageView.as_view(), name='home'),
    url(r'^gocd/user/', include('apps.user.urls', namespace='user')),
    url(r'^gocd/project/', include('apps.project.urls', namespace='project')),
]


if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.conf.urls.static import static
    from django.views.generic import TemplateView

    urlpatterns += staticfiles_urlpatterns()

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

    urlpatterns += [
        url(r'^404/$', TemplateView.as_view(template_name='404.html')),
    ]

sites/gocd-interface/apps/user/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from apps.user import views


urlpatterns = patterns('',
    url(r'^$', login_required(views.UserListView.as_view()), name="user-list"),
    url(r'^create/', login_required(views.UserCreateView.as_view()), name="create"),
)

sites/gocd-interface/apps/forms.py
import urlparse

from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from django.core import validators


class LoginForm(AuthenticationForm):
    # Username field must be the same length as the email field
    username = forms.CharField(
        label=_("Username"), max_length=75,
        widget=forms.TextInput(attrs={'autocomplete': 'off'}))
    password = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'off'}))
    redirect_url = forms.CharField(
        widget=forms.HiddenInput, required=False)

    def __init__(self, host, *args, **kwargs):
        self.host = host
        super(LoginForm, self).__init__(*args, **kwargs)
        self.error_messages['invalid_login'] = _(
            "Please enter a correct e-mail and password. "
            "Note that the password is case-sensitive.")

    def clean_redirect_url(self):
        url = self.cleaned_data['redirect_url'].strip()
        if not url:
            return settings.LOGIN_REDIRECT_URL
        host = urlparse.urlparse(url)[1]
        if host and host != self.host:
            return settings.LOGIN_REDIRECT_URL
        return url


class ForgotPasswordForm(forms.Form):
    username = forms.CharField(label=_("Username"))


class PasswordResetForm(forms.Form):
    password_validators = [validators.MinLengthValidator(8)]

    password = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'off'}),
        validators=password_validators)
    confirm_password = forms.CharField(
        label=_("Confirm Password"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'off'}))

    def clean_password(self):
        # Can't use cleaned_data for confirm_password as it may not have been
        # cleaned yet
        if not self.cleaned_data['password'] == self.data['confirm_password']:
            raise forms.ValidationError(_("Passwords do not match!"))
        return self.cleaned_data['password']

sites/gocd-interface/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" lang="en" content="GOCD interface">
        <meta name="robots" content="index, follow">

        <!-- icons -->
        <link rel="apple-touch-icon" href=" {% static "img/apple-touch-icon.png" %}">
        <link rel="shortcut icon" href="favicon.ico">
        <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">

        <!-- Bootstrap Core CSS file -->
        <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">

        <!-- Override CSS file - add your own CSS rules -->
        <link rel="stylesheet" href="{% static "css/styles.css" %}">

        <!-- Conditional comment containing JS files for IE6 - 8 -->
        <!--[if lt IE 9]>
            <script src="assets/js/html5.js"></script>
            <script src="assets/js/respond.min.js"></script>
        <![endif]-->
        {% block extra_head %}
        {% endblock %}
    </head>
    <body>
    {% block layout %}
    {% endblock layout %}

    <!-- JQuery scripts -->
    <script src="{% static "js/jquery-1.11.2.min.js" %}"></script>

    <!-- Bootstrap Core scripts -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    {% block extra_scripts %}
    {% endblock extra_scripts %}
  </body>
</html>

sites/gocd-interface/templates/forgotten-password.html
{% extends 'layout.html' %}
{% load staticfiles %}

{% block title %}{{ block.super }} | Login {% endblock %}

{% block content %}
    <h1>Reset Password</h1>

    <form method="post" name="forgotten-pass" id="forgotten-pass" action="{% url "forgotten-password" %}" class="form">
        <fieldset>
            {% csrf_token %}
            <div class="form-group">
                <div class="field {% if form.username.errors %}error{% endif %}">
                    <input id="id_username" name="username" type="text" class="form-control" placeholder="Enter Username">
                    <div class="errormsg">{% if form.username.errors %}{{ form.username.errors }}{% endif %}</div>
                </div>
            </div>
            <div class="buttons">
                <button type="submit" class="btn">Submit</button>
            </div>
        </fieldset>
    </form>
{% endblock %}

{% block sidebar %}
{% endblock sidebar %}

sites/gocd-interface/templates/home.html
{% extends "layout.html" %}

{% block page-header %}
<h1>Home Page</h1>
{% endblock %}

{% block content %}
{% endblock content %}

sites/gocd-interface/templates/layout.html
{% extends "base.html" %}

{% load staticfiles %}

{% block layout %}
    {% block header %}
    <!-- Navigation -->
    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
        <div class="container-fluid">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                {% if user.is_authenticated %}
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                {% endif %}
                <a class="navbar-brand" href="/">{% block site-logo %}GOCD Interface{% endblock site-logo %}</a>
            </div>
            <!-- /.navbar-header -->

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbar-collapse">
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'user:user-list' %}">Users</a>
                    </li>
                    <li>
                        <a href="{% url 'project:project-list' %}">Projects</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                    <li><a href="{% url "logout" %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                </ul>
                {% endif %}
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    <!-- /.navbar -->
    {% endblock %}

    <!-- Page Content -->
    <div class="container-fluid">
        {% block container %}
        <div class="row">
            <div class="col-sm-12">
                <div class="page-header">
                {% block page-header %}
                {% endblock %}
                </div>
            </div>
        </div>

        <!-- /.row -->

        <div class="row">
            {% block messages %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            <a href="#" class="close" data-dismiss="alert">&times;</a>
                            {{ message.message|linebreaksbr }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endblock %}
            <div class="col-sm-8">
            {% block content %}
            {% endblock content %}
            </div>
        {% endblock container %}
        </div>
        <!-- /.row -->

        {% block footer %}
        <hr>
        <footer class="margin-tb-3">
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; {% block footer-sitename %}{% endblock footer-sitename %} {% now 'Y' %}</p>
                </div>
            </div>
        </footer>
        {% endblock footer %}
    </div>
    <!-- /.container-fluid -->

    {% endblock layout %}

    <!-- JQuery scripts -->
    <script src="{% static "js/jquery-1.11.2.min.js" %}"></script>

    <!-- Bootstrap Core scripts -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>

sites/gocd-interface/templates/login.html
{% extends 'layout.html' %}
{% load staticfiles %}

{% block title %}{{ block.super }} | Login {% endblock %}

{% block content %}
    <h1>Log in</h1>
    <p>Please enter your username and password to continue.</p>

    {% if form.errors %}
        <div class="alert">
            <a href="#" class="close">&times;</a>
            <strong>Your username and password didn't match.</strong> Please try again.
        </div>
    {% endif %}

    <form method="post" action="{% url 'login' %}" class="form">
        <fieldset>
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            <input type="hidden" class="input input--block" name="next" value="{{ next }}" />

            <div class="form-group">
                <div class="{% if form.username.errors %}error{% endif %}">
                    <input type="text" name="{{ form.username.name }}" id="id_{{ form.username.name }}" autocomplete="off" class="form-control" placeholder="Username"></input>
                    <div class="errormsg">{% if form.username.errors %}{{ form.username.errors }}{% endif %}</div>
                </div>
            </div>
            <div class="form-group">
                <div class="{% if form.username.errors %}error{% endif %}">
                    <input type="password" name="{{ form.password.name }}" id="id_{{ form.password.name }}" autocomplete="off" class="form-control" placeholder="Password"></input>
                    <div class="errormsg">{% if form.password.errors %}{{ form.password.errors }}{% endif %}</div>
                </div>
            </div>

            <div class="form-group pull-right">
                <a href="{% url 'forgotten-password' %}">Forgot your password?</a>
            </div>

            <div class="buttons">
                <button type="submit" class="btn">Login</button>
            </div>
        </fieldset>

    </form>
{% endblock %}

{% block sidebar %}
{% endblock sidebar %}

sites/gocd-interface/templates/reset-password.html
{% extends 'layout.html' %}
{% load staticfiles %}

{% block title %}{{ block.super }} | Login {% endblock %}

{% block content %}
    <h1>Set Password</h1>

    <form method="post" name="reset-password" id="reset-password" class="form" action="{% url "reset-forgotten-password" unique_code=unique_code %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_password">Password:</label>
            <input autocomplete="off" id="id_password" name="password" type="password" class="form-control">
        </div>
        <div class="form-group">
            <label for="id_confirm_password">Confirm Password:</label>
            <input autocomplete="off" id="id_confirm_password" name="confirm_password" type="password" class="form-control">
        </div>
        <div class="buttons">
            <button type="submit" class="btn">Submit</button>
        </div>
    </form>
{% endblock %}

{% block sidebar %}
{% endblock sidebar %}