sites/gocd-interface/apps/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

from apps.decorators import login_forbidden
from apps import views


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', login_forbidden(views.LoginView.as_view()), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^forgotten-password/$', views.ForgottenPasswordView.as_view(), name="forgotten-password"),
    url(r'^reset-forgotten-password/(?P<unique_code>[a-zA-Z0-9\-]+)/', views.PasswordResetView.as_view(), name="reset-forgotten-password"),
    url(r'^password-set/(?P<unique_code>[a-zA-Z0-9\-]+)/', views.PasswordResetView.as_view(), name="set-password"),
    url(r'^gocd/$', views.HomePageView.as_view(), name='home'),
    url(r'^gocd/user/', include('apps.user.urls', namespace='user')),
    url(r'^gocd/project/', include('apps.project.urls', namespace='project')),
]


if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.conf.urls.static import static
    from django.views.generic import TemplateView

    urlpatterns += staticfiles_urlpatterns()

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

    urlpatterns += [
        url(r'^404/$', TemplateView.as_view(template_name='404.html')),
    ]

sites/gocd-interface/apps/user/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from apps.user import views


urlpatterns = patterns('',
    url(r'^$', login_required(views.UserListView.as_view()), name="user-list"),
    url(r'^create/', login_required(views.UserCreateView.as_view()), name="create"),
)

sites/gocd-interface/apps/user/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager  # pragma: no cover
from django.db import models  # pragma: no cover
from django.conf import settings  # pragma: no cover


# Managers
class UserManager(BaseUserManager):  # pragma: no cover
    def create_user(self, username, email, password=None, **extra_fields):
        user = self.model(username=username,
                          email=UserManager.normalize_email(email))

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password, **extra_fields):
        user = self.create_user(username,
                                email,
                                password=password)
        user.is_admin = True
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):  # pragma: no cover
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField(max_length=300, unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    first_login = models.DateTimeField(auto_now_add=True)
    is_staff = models.BooleanField(default=False, null=False)
    is_superuser = models.BooleanField(default=False, null=False)
    is_active = models.BooleanField(default=True, null=False)
    date_joined = models.DateTimeField(auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def get_full_name(self):
        if self.first_name:
            return "%s %s" % (self.first_name, self.last_name)
        return self.username

    def get_short_name(self):
        return self.username

    def __unicode__(self):
        return self.username

    def __str__(self):
        return str(self.__unicode__())

    def has_perm(self, perm, obj=None):
        # Simplest possible answer: Yes, always
        if self.is_superuser:
            return True
        return True

    def has_module_perms(self, app_label):
        # Simplest possible answer: Yes, always
        if self.is_superuser:
            return True
        return True


class PasswordLink(models.Model):  # pragma: no cover
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='User')
    code = models.CharField(max_length=50)
    used = models.DateTimeField(null=True)
    is_invite = models.BooleanField(default=False)
    created_dt = models.DateTimeField(auto_now_add=True)
    modified_dt = models.DateTimeField(auto_now=True)


class Role(models.Model):  # pragma: no cover
    name = models.CharField(max_length=255)
    role_type = models.CharField(max_length=255, unique=True)
    users = models.ManyToManyField('user.User', related_name="roles")

sites/gocd-interface/apps/user/forms.py
import urlparse

from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.conf import settings


class LoginForm(AuthenticationForm):
    # Username field must be the same length as the email field
    username = forms.CharField(
        label=_("Username"), max_length=75,
        widget=forms.TextInput(attrs={'autocomplete': 'off'}))
    password = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'off'}))
    redirect_url = forms.CharField(
        widget=forms.HiddenInput, required=False)

    def __init__(self, host, *args, **kwargs):
        self.host = host
        super(LoginForm, self).__init__(*args, **kwargs)
        self.error_messages['invalid_login'] = _(
            "Please enter a correct e-mail and password. "
            "Note that the password is case-sensitive.")

    def clean_redirect_url(self):
        url = self.cleaned_data['redirect_url'].strip()
        if not url:
            return settings.LOGIN_REDIRECT_URL
        host = urlparse.urlparse(url)[1]
        if host and host != self.host:
            return settings.LOGIN_REDIRECT_URL
        return url


class CreateUserForm(forms.Form):
    username = forms.CharField(max_length=100)
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=300)

sites/gocd-interface/apps/user/views.py
from django.views.generic import FormView, RedirectView, TemplateView
from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
from django.contrib.auth import logout, login
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib import messages

from apps.user import forms
from apps.user.services import UserService


class UserListView(TemplateView):
    template_name = "user/user-list.html"

    def get_context_data(self, *args, **kwargs):
        context = super(UserListView, self).get_context_data(*args, **kwargs)
        context['users'] = UserService().get_all_users()
        return context


class UserCreateView(FormView):
    template_name = "user/create.html"
    form_class = forms.CreateUserForm

    def form_valid(self, form, *args, **kwargs):
        messages.add_message(self.request, messages.SUCCESS, "Created new user")
        service = UserService()
        user, created = service.create_user(
            form.cleaned_data['username'],
            form.cleaned_data['email'],
            first_name=form.cleaned_data['first_name'],
            last_name=form.cleaned_data['last_name'])
        if created:
            service.send_user_password_invite(user)

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('user:user-list')

sites/gocd-interface/templates/user/create.html
{% extends "layout.html" %}

{% block page-header %}
<h1>Users</h1>
{% endblock %}

{% block content %}
<form method="post" action="{% url 'user:create' %}" class="form">
    <fieldset>
        {% csrf_token %}
        <div class="form-group">
            <div class="{% if form.username.errors %}error{% endif %}">
                <input type="text" name="{{ form.username.name }}" id="id_{{ form.username.name }}" class="form-control" placeholder="Username"{% if form.username.value %} value="{{ form.username.value }}"{% endif %}></input>
                <div class="errormsg">{% if form.username.errors %}{{ form.username.errors }}{% endif %}</div>
            </div>
        </div>
        <div class="form-group">
            <div class="{% if form.first_name.errors %}error{% endif %}">
                <input type="text" name="{{ form.first_name.name }}" id="id_{{ form.first_name.name }}" class="form-control" placeholder="First Name"{% if form.first_name.value %} value="{{ form.first_name.value }}"{% endif %}></input>
                <div class="errormsg">{% if form.first_name.errors %}{{ form.first_name.errors }}{% endif %}</div>
            </div>
        </div>
        <div class="form-group">
            <div class="{% if form.last_name.errors %}error{% endif %}">
                <input type="text" name="{{ form.last_name.name }}" id="id_{{ form.last_name.name }}" class="form-control" placeholder="Last Name"{% if form.last_name.value %} value="{{ form.last_name.value }}"{% endif %}></input>
                <div class="errormsg">{% if form.last_name.errors %}{{ form.last_name.errors }}{% endif %}</div>
            </div>
        </div>
        <div class="form-group">
            <div class="{% if form.email.errors %}error{% endif %}">
                <input type="email" name="{{ form.email.name }}" id="id_{{ form.email.name }}" class="form-control" placeholder="Email"{% if form.email.value %} value="{{ form.email.value }}"{% endif %}></input>
                <div class="errormsg">{% if form.email.errors %}{{ form.email.errors }}{% endif %}</div>
            </div>
        </div>

        <div class="buttons">
            <button type="submit" class="btn">Create</button>
        </div>
    </fieldset>

</form>

{% endblock content %}

sites/gocd-interface/templates/user/user-list.html
{% extends "layout.html" %}

{% block page-header %}
<h1>Users</h1>
{% endblock %}

{% block content %}
    <a href="{% url 'user:create' %}" class="btn btn-default pull-right"><span class="glyphicon glyphicon-plus"></span> Create new user</a>

    <table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Username</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Status</th>
            <th></th>
        </tr>
    </thead>
    {% for user in users %}
        <tr>
            <td>{{ user.username }}</td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.last_name }}</td>
            <td>{% if user.is_active %}Active{% else %}Inactive{% endif %}</td>
            <td>
                {% if user.pk == request.user.pk %}<span class="label label-pill label-primary">This is you</span>{% endif %}
                {% for role in user.roles.all %}
                {% if role.role_type = 'admin' %}<span class="label label-pill label-danger">Admin</span>{% endif %}
                {% endfor %}
            </td>
        </tr>
    {% endfor %}
    </table>
    <a href="{% url 'user:create' %}" class="btn btn-default pull-right"><span class="glyphicon glyphicon-plus"></span> Create new user</a>
{% endblock content %}