sites/gocd-interface/apps/project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from apps.project import views


urlpatterns = patterns('',
    url(r'^$', login_required(views.ProjectListView.as_view()), name="project-list"),
    url(r'^create/', login_required(views.ProjectCreateView.as_view()), name="create"),
    url(r'^(?P<pk>\d+)/settings/', login_required(views.ProjectSettingsView.as_view()), name="settings"),
    url(r'^(?P<pk>\d+)/', login_required(views.ProjectDetailView.as_view()), name="detail"),
)

sites/gocd-interface/apps/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

from apps.decorators import login_forbidden
from apps import views


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', login_forbidden(views.LoginView.as_view()), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^forgotten-password/$', views.ForgottenPasswordView.as_view(), name="forgotten-password"),
    url(r'^reset-forgotten-password/(?P<unique_code>[a-zA-Z0-9\-]+)/', views.PasswordResetView.as_view(), name="reset-forgotten-password"),
    url(r'^password-set/(?P<unique_code>[a-zA-Z0-9\-]+)/', views.PasswordResetView.as_view(), name="set-password"),
    url(r'^gocd/$', views.HomePageView.as_view(), name='home'),
    url(r'^gocd/user/', include('apps.user.urls', namespace='user')),
    url(r'^gocd/project/', include('apps.project.urls', namespace='project')),
]


if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.conf.urls.static import static
    from django.views.generic import TemplateView

    urlpatterns += staticfiles_urlpatterns()

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

    urlpatterns += [
        url(r'^404/$', TemplateView.as_view(template_name='404.html')),
    ]

sites/gocd-interface/apps/project/models.py
from django.db import models


class Project(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=1024)
    members = models.ManyToManyField('project.ProjectMember', blank=True)
    owner = models.ForeignKey('user.User')
    visible_to_all = models.BooleanField(default=False)
    gocd_server_host = models.CharField(max_length=255)
    gocd_server_port = models.IntegerField()
    gocd_server_username = models.CharField(max_length=255)
    gocd_server_password = models.CharField(max_length=255)


class PipelineGroup(models.Model):
    project = models.ForeignKey('project.Project')
    name = models.CharField(max_length=255)
    gocd_name = models.CharField(max_length=255)


class ProjectMember(models.Model):
    ADMIN = 'admin'
    MEMBER = 'member'
    VIEWER = 'viewer'

    LEVEL_CHOICES = (
        (ADMIN, 'Admin'),
        (MEMBER, 'Member'),
        (VIEWER, 'Viewer'))

    user = models.ForeignKey('user.User')
    member_level = models.CharField(max_length=100,
                                    choices=LEVEL_CHOICES)

sites/gocd-interface/apps/project/forms.py
from django import forms


class ProjectForm(forms.Form):
    name = forms.CharField(max_length=255)
    description = forms.CharField(max_length=1024, widget=forms.Textarea)
    visible_to_all = forms.BooleanField(required=False)
    gocd_server_host = forms.CharField(max_length=255)
    gocd_server_port = forms.IntegerField()
    gocd_server_username = forms.CharField(max_length=255)
    gocd_server_password = forms.CharField(
        max_length=255,
        widget=forms.PasswordInput(attrs={'autocomplete': 'off'}))


class ProjectMembersForm(forms.Form):
    name = forms.CharField(max_length=255)
    description = forms.CharField(max_length=1024, widget=forms.Textarea)
    visible_to_all = forms.BooleanField(required=False)

sites/gocd-interface/apps/project/views.py
from django.views.generic import FormView, RedirectView, TemplateView
from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
from django.contrib.auth import logout, login
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib import messages

from apps.project.services import ProjectService
from apps.project.forms import ProjectForm, ProjectMembersForm
from apps.gocd.services import GOCDService


class ProjectListView(TemplateView):
    template_name = "project/project-list.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProjectListView, self).get_context_data(*args, **kwargs)
        context['projects'] = ProjectService().get_all_projects()
        return context


class ProjectCreateView(FormView):
    template_name = "project/create.html"
    form_class = ProjectForm

    def form_valid(self, form, *args, **kwargs):
        messages.add_message(
            self.request, messages.SUCCESS, "Created new project")
        service = ProjectService()
        project = service.create_project(
            self.request.user,
            form.cleaned_data['name'],
            form.cleaned_data['description'],
            visible_to_all=form.cleaned_data['visible_to_all'])

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('project:project-list')


class ProjectSettingsView(TemplateView):
    template_name = "project/settings.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProjectSettingsView, self).get_context_data(*args, **kwargs)
        project = ProjectService().get_project_by_pk(self.kwargs['pk'])
        context['project_form'] = ProjectForm(
            initial=self.get_project_initial(project))
        context['project_members_form'] = ProjectMembersForm(
            initial=self.get_project_members_initial())
        return context

    def get_project_initial(self, project):
        return {'name': project.name,
                'description': project.description,
                'visible_to_all': project.visible_to_all,
                'gocd_server_host': project.gocd_server_host,
                'gocd_server_port': project.gocd_server_port,
                'gocd_server_username': project.gocd_server_username,
                'gocd_server_password': project.gocd_server_password}

    def get_project_members_initial(self):
        return {}


class ProjectDetailView(TemplateView):
    template_name = "project/detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProjectDetailView, self).get_context_data(*args, **kwargs)
        project = ProjectService().get_project_by_pk(self.kwargs['pk'])
        context['project'] = project
        status, reason = GOCDService().test_connection(
            project.gocd_server_host, project.gocd_server_port,
            project.gocd_server_username, project.gocd_server_password)
        context['gocd_connection'] = status
        context['gocd_reason'] = reason
        pipeline_groups = GOCDService().get_pipeline_groups(
            project.gocd_server_host, project.gocd_server_port,
            project.gocd_server_username, project.gocd_server_password)
        context['pipeline_groups'] = ProjectService().get_groups_for_project(
            project, pipeline_groups)
        return context

sites/gocd-interface/templates/project/create.html
{% extends "layout.html" %}

{% block page-header %}
<h1>Project Creation</h1>
{% endblock %}

{% block content %}
<form method="post" action="{% url 'project:create' %}" class="form">
    <fieldset>
        {% csrf_token %}
        <div class="form-group">
            <div class="{% if form.name.errors %}error{% endif %}">
                <input type="text" name="{{ form.name.name }}" id="id_{{ form.name.name }}" class="form-control" placeholder="Name"{% if form.name.value %} value="{{ form.name.value }}"{% endif %}></input>
                <div class="errormsg">{% if form.name.errors %}{{ form.name.errors }}{% endif %}</div>
            </div>
        </div>
        <div class="form-group">
            <div class="{% if form.description.errors %}error{% endif %}">
                <textarea name="{{ form.description.name }}" id="id_{{ form.description.name }}" class="form-control" placeholder="Description"{% if form.description.value %} value="{{ form.description.value }}"{% endif %}></textarea>
                <div class="errormsg">{% if form.description.errors %}{{ form.description.errors }}{% endif %}</div>
            </div>
        </div>
        <div class="form-group">
            <div class="{% if form.visible_to_all.errors %}error{% endif %}">
                <label for="id_visible_to_all">Visible to all</label>
                <input type="checkbox" name="{{ form.visible_to_all.name }}" id="id_{{ form.visible_to_all.name }}" class="form-control" {% if form.visible_to_all.value %} checked="{{ form.visible_to_all.value }}"{% endif %}></input>
                <div class="errormsg">{% if form.visible_to_all.errors %}{{ form.visible_to_all.errors }}{% endif %}</div>
            </div>
        </div>

        <div class="buttons">
            <button type="submit" class="btn">Create</button>
        </div>
    </fieldset>
</form>

{% endblock content %}

sites/gocd-interface/templates/project/detail.html
{% extends "layout.html" %}

{% block page-header %}
<h1>{{ project.name }}</h1>
{% endblock %}

{% block content %}
<div>GOCD Connection is: <strong>{% if gocd_connection %}OK{% else %}{{ gocd_reason }}{% endif %}</strong></div>
{% endblock content %}

sites/gocd-interface/templates/project/project-list.html
{% extends "layout.html" %}

{% block page-header %}
<h1>Projects</h1>
{% endblock %}

{% block content %}
    {% if projects.count > 0 %}
    <a href="{% url 'project:create' %}" class="btn btn-default pull-right"><span class="glyphicon glyphicon-plus"></span> Create new project</a>

    <table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Name</th>
            <th></th>
        </tr>
    </thead>
    {% for project in projects %}
        <tr>
            <td><a href="{% url 'project:detail' pk=project.pk %}">{{ project.name }}</a></td>
            <td><a href="{% url 'project:settings' pk=project.pk %}"><span class="glyphicon glyphicon-cog pull-right"></span></a></td>
        </tr>
    {% endfor %}
    </table>
    <a href="{% url 'project:create' %}" class="btn btn-default pull-right"><span class="glyphicon glyphicon-plus"></span> Create new project</a>
    {% else %}
    <div>
    You have no projects
    </div>
    <a href="{% url 'project:create' %}" class="btn btn-default pull-right"><span class="glyphicon glyphicon-plus"></span> Create new project</a>
    {% endif %}

{% endblock content %}

sites/gocd-interface/templates/project/settings.html
{% extends "layout.html" %}

{% block page-header %}
<h1>Settings</h1>
{% endblock %}

{% block content %}
<h2>Project Settings</h2>
<form method="post" action="." class="form">
    <fieldset>
        {% csrf_token %}
        <div class="form-group">
            <div class="{% if project_form.name.errors %}error{% endif %}">
                <input type="text" name="{{ project_form.name.name }}" id="id_{{ project_form.name.name }}" class="form-control" placeholder="Name"{% if project_form.name.value %} value="{{ project_form.name.value }}"{% endif %}></input>
                <div class="errormsg">{% if project_form.name.errors %}{{ project_form.name.errors }}{% endif %}</div>
            </div>
        </div>
        <div class="form-group">
            <div class="{% if project_form.description.errors %}error{% endif %}">
                <textarea name="{{ project_form.description.name }}" id="id_{{ project_form.description.name }}" class="form-control" placeholder="Description"{% if project_form.description.value %} value="{{ project_form.description.value }}"{% endif %}></textarea>
                <div class="errormsg">{% if project_form.description.errors %}{{ project_form.description.errors }}{% endif %}</div>
            </div>
        </div>
        <div class="form-group">
            <div class="{% if project_form.visible_to_all.errors %}error{% endif %}">
                <label for="id_visible_to_all">Visible to all</label>
                <input type="checkbox" name="{{ project_form.visible_to_all.name }}" id="id_{{ project_form.visible_to_all.name }}" class="form-control" {% if project_form.visible_to_all.value %} checked="{{ project_form.visible_to_all.value }}"{% endif %}></input>
                <div class="errormsg">{% if project_form.visible_to_all.errors %}{{ project_form.visible_to_all.errors }}{% endif %}</div>
            </div>
        </div>

        <div class="form-group">
            <div class="{% if project_form.gocd_server_host.errors %}error{% endif %}">
                <input type="text" name="{{ project_form.gocd_server_host.name }}" id="id_{{ project_form.gocd_server_host.name }}" class="form-control" placeholder="GOCD Host"{% if project_form.gocd_server_host.value %} value="{{ project_form.gocd_server_host.value }}"{% endif %}></input>
                <div class="errormsg">{% if project_form.gocd_server_host.errors %}{{ project_form.gocd_server_host.errors }}{% endif %}</div>
            </div>
        </div>
        <div class="form-group">
            <div class="{% if project_form.gocd_server_port.errors %}error{% endif %}">
                <input type="text" name="{{ project_form.gocd_server_port.name }}" id="id_{{ project_form.gocd_server_port.name }}" class="form-control" placeholder="GOCD Port"{% if project_form.gocd_server_port.value %} value="{{ project_form.gocd_server_port.value }}"{% endif %}></input>
                <div class="errormsg">{% if project_form.gocd_server_port.errors %}{{ project_form.gocd_server_port.errors }}{% endif %}</div>
            </div>
        </div>
        <div class="form-group">
            <div class="{% if project_form.gocd_server_username.errors %}error{% endif %}">
                <input type="text" name="{{ project_form.gocd_server_username.name }}" id="id_{{ project_form.gocd_server_username.name }}" class="form-control" placeholder="GOCD Username"{% if project_form.gocd_server_username.value %} value="{{ project_form.gocd_server_username.value }}"{% endif %}></input>
                <div class="errormsg">{% if project_form.gocd_server_username.errors %}{{ project_form.gocd_server_username.errors }}{% endif %}</div>
            </div>
        </div>
        <div class="form-group">
            <div class="{% if project_form.gocd_server_password.errors %}error{% endif %}">
                <input type="password" name="{{ project_form.gocd_server_password.name }}" id="id_{{ project_form.gocd_server_password.name }}" class="form-control" placeholder="GOCD Password"{% if project_form.gocd_server_password.value %} autocomplete="off" value="{{ project_form.gocd_server_password.value }}"{% endif %}></input>
                <div class="errormsg">{% if project_form.gocd_server_password.errors %}{{ project_form.gocd_server_password.errors }}{% endif %}</div>
            </div>
        </div>

        <div class="buttons">
            <button type="submit" class="btn">Update</button>
        </div>
    </fieldset>
</form>
<h2>Project Members</h2>
{% endblock content %}